package com.diplomat.domain.model

/**
 * Lifecycle of a captured message as it moves through the Grey Rock flow.
 */
enum class MessageStatus {
    /** Captured, waiting for the user to make a decision. */
    PENDING_DECISION,

    /** A draft reply is being generated by the backend. */
    DRAFTING,

    /** A toned-down draft reply is ready for review. */
    DRAFTED,

    /** The user approved and dispatched a reply. */
    SENT,

    /** The user chose to ignore the message (acknowledged, no reply). */
    IGNORED_ACK,

    /** Something failed while analyzing or drafting. */
    ERROR,
}
